services:
  - type: web
    name: sistema-de-incidencias-v2
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
